"""Closed production writer families for the vNext physical-domain contracts.

This registry is deliberately executable wheel code.  It names installed
repository method objects and installed :mod:`h2hdb.vnext_domains` guards;
neither callback markers nor generated DDL checks count as a binding.
"""

from __future__ import annotations

__all__ = [
    "CATALOG_PHYSICAL_DOMAIN_GUARDS",
    "CATALOG_PHYSICAL_DOMAIN_MUTATION_RELATIONS",
    "CATALOG_PHYSICAL_DOMAIN_READ_ONLY_RELATIONS",
    "CATALOG_PHYSICAL_DOMAIN_RELATIONS",
    "CATALOG_PHYSICAL_DOMAIN_WRITERS",
    "OPERATIONAL_PHYSICAL_DOMAIN_GUARDS",
    "OPERATIONAL_PHYSICAL_DOMAIN_MUTATION_RELATIONS",
    "OPERATIONAL_PHYSICAL_DOMAIN_RELATIONS",
    "OPERATIONAL_PHYSICAL_DOMAIN_WRITERS",
    "OPERATIONAL_SCHEMA_EPOCH_WRITERS",
]

from collections.abc import Callable
from typing import Any

from . import vnext_domains
from .schema_epoch import SchemaEpochRunner
from .vnext_analysis_repository import AnalysisRepository
from .vnext_artifact_preparation_repository import ArtifactPreparationRepository
from .vnext_artifact_release_repository import ArtifactReleaseRepository
from .vnext_canonical_value_repository import CanonicalValueRepository
from .vnext_cleanup_repository import VNextCleanupRepository
from .vnext_gallery_identity_repository import GalleryIdentityRepository
from .vnext_gallery_staging_repository import GalleryObservationStagingRepository
from .vnext_operational_event_repository import OperationalEffectRepository
from .vnext_publication_candidate_repository import PublicationCandidateRepository
from .vnext_publication_finalization_repository import (
    PublicationFinalizationRepository,
)
from .vnext_publication_repository import PublicationRepository
from .vnext_queue_repository import VNextQueueRepository
from .vnext_source_build_repository import SourceBuildRepository

type PhysicalDomainEntrypoint = Callable[..., object]
type PhysicalDomainGuard = Callable[..., Any]


CATALOG_PHYSICAL_DOMAIN_RELATIONS = frozenset(
    {
        "canonical_value_allocation_anchor",
        "canonical_value_allocation_digest_domain",
        "canonical_value_allocation_byte_count",
        "canonical_value_allocation_allocated_at",
        "canonical_value_allocation_seal",
        "canonical_value_allocation",
        "canonical_value_page_anchor",
        "canonical_value_page_payload",
        "canonical_value_page_coordinate",
        "canonical_value_page_subtree_item_count",
        "canonical_value_page_seal",
        "canonical_value_page",
        "canonical_value_page_descriptor",
        "canonical_value_page_parent",
        "source_locator_identity",
        "gallery_identity",
        "file_name_identity_anchor",
        "file_name_identity_name_bytes",
        "file_name_identity_file_role",
        "file_name_identity_seal",
        "file_name_identity",
        "gallery_observation_file_anchor",
        "gallery_observation_file_file_no",
        "gallery_observation_file_file_sha256",
        "gallery_observation_file_seal",
        "gallery_observation_file",
        "tag_term_anchor",
        "tag_term_identity",
        "tag_term_seal",
        "tag_term",
        "source_build_anchor",
        "source_build_scope_key",
        "source_build_manifest_policy_id",
        "source_build_state",
        "source_build_created_at",
        "source_build_descriptor_seal",
        "source_build_sealed_at",
        "source_build",
        "source_build_discovery_gallery_count",
        "build_manifest_anchor",
        "build_manifest_manifest_sha256",
        "build_manifest_file_count",
        "build_manifest_byte_count",
        "build_manifest_seal",
        "build_manifest",
        "gallery_manifest_anchor",
        "gallery_manifest_manifest_sha256",
        "gallery_manifest_computed_at",
        "gallery_manifest_seal",
        "gallery_manifest",
        "source_snapshot_manifest_identity_anchor",
        "source_snapshot_manifest_identity_gallery_count",
        "source_snapshot_manifest_identity_file_count",
        "source_snapshot_manifest_identity_byte_count",
        "source_snapshot_manifest_identity_seal",
        "source_snapshot_manifest_identity",
        "publication_identity",
        "artifact_location",
        "artifact_producer_fingerprint_anchor",
        "artifact_producer_fingerprint_algorithm_version",
        "artifact_producer_fingerprint_equivalence_class",
        "artifact_producer_fingerprint_identity",
        "artifact_producer_fingerprint_seal",
        "artifact_producer_fingerprint",
        "artifact_storage_codec",
        "artifact_semantic_input_anchor",
        "artifact_semantic_input_source_manifest_component_sha256",
        "artifact_semantic_input_member_plan_component_sha256",
        "artifact_semantic_input_effective_content_component_sha256",
        "artifact_semantic_input_selected_component_sha256",
        "artifact_semantic_input_owner_component_sha256",
        "artifact_semantic_input_policy_component_sha256",
        "artifact_semantic_input_identity",
        "artifact_semantic_input_seal",
        "artifact_semantic_input",
        "prepared_artifact_anchor",
        "prepared_artifact_sha256",
        "prepared_artifact_storage_codec_version",
        "prepared_artifact_storage_generation",
        "prepared_artifact_protection_token",
        "prepared_artifact_state",
        "prepared_artifact_seal",
        "catalog_artifact_anchor",
        "catalog_artifact_sha256",
        "catalog_artifact_semantics_sha256",
        "catalog_artifact_seal",
        "catalog_artifact",
        "gallery_observation_page",
        "gallery_observation_allocation_page",
        "gallery_observation_page_descriptor_anchor",
        "gallery_observation_page_descriptor_component",
        "gallery_observation_page_descriptor_level",
        "gallery_observation_page_descriptor_subtree_item_count",
        "gallery_observation_page_descriptor_seal",
        "gallery_observation_page_descriptor",
        "gallery_observation_page_key_bounds_anchor",
        "gallery_observation_page_key_bounds_first_key",
        "gallery_observation_page_key_bounds_last_key",
        "gallery_observation_page_key_bounds_seal",
        "gallery_observation_page_key_bounds",
        "gallery_observation_page_child",
        "gallery_observation_discovery_fingerprint",
        "analysis_run_anchor",
        "analysis_run_build_id",
        "analysis_run_policy_id",
        "analysis_run_input_manifest_sha256",
        "analysis_run_identity",
        "analysis_run_started_at",
        "analysis_run_state",
        "analysis_run_descriptor_seal",
        "analysis_run_completed_at",
        "analysis_run",
        "analysis_state_anchor",
        "analysis_state_component_anchor",
        "analysis_state_component_row_count",
        "analysis_state_component_sealed_at",
        "analysis_state_component_completion_seal",
        "analysis_state_component_seal",
        "analysis_exclusion_delta_anchor",
        "analysis_exclusion_delta_old_excluded",
        "analysis_exclusion_delta_new_excluded",
        "analysis_exclusion_delta_change",
        "analysis_exclusion_delta_seal",
        "analysis_exclusion_delta",
        "analysis_file_hash_decision_shadow_anchor",
        "analysis_file_hash_decision_shadow_occurrence_count",
        "analysis_file_hash_decision_shadow_artist_count",
        "analysis_file_hash_decision_shadow_maximum_gallery_artist_count",
        "analysis_file_hash_decision_shadow_seal",
        "analysis_file_hash_decision_shadow",
        "analysis_content_owner_candidate_shadow_anchor",
        "analysis_content_owner_candidate_shadow_content_sha256",
        "analysis_content_owner_candidate_shadow_prefer_not_already_uploaded",
        "analysis_content_owner_candidate_shadow_title_scalar_count",
        "analysis_content_owner_candidate_shadow_download_time",
        "analysis_content_owner_candidate_shadow_seal",
        "analysis_content_owner_candidate_shadow",
        "analysis_content_owner_shadow_anchor",
        "analysis_content_owner_shadow_owner_gallery_id",
        "analysis_content_owner_shadow_seal",
        "analysis_content_owner_shadow",
        "analysis_impacted_content_anchor",
        "analysis_impacted_content_provenance",
        "analysis_impacted_content_witness",
        "analysis_impacted_content_seal",
        "analysis_impacted_content",
        "analysis_impacted_gid_anchor",
        "analysis_impacted_gid_provenance",
        "analysis_impacted_gid_witness",
        "analysis_impacted_gid_seal",
        "analysis_impacted_gid",
        "analysis_gid_candidate_shadow",
        "analysis_gid_candidate_tombstone",
        "analysis_gid_candidate_resolved",
        "analysis_gid_winner_selection",
        "analysis_gid_winner_shadow",
        "analysis_gid_winner_tombstone",
        "analysis_gid_winner_resolved",
        "analysis_batch_receipt_page_limit",
        "analysis_checkpoint",
        "publication_checkpoint",
        "publication_batch_receipt",
        "publication_candidate_anchor",
        "publication_candidate_analysis_id",
        "publication_candidate_reserved_revision",
        "publication_candidate_artifact_policy_id",
        "publication_candidate_display_title_policy_id",
        "publication_candidate_artifacts_required",
        "publication_candidate_created_at",
        "publication_candidate_definition_seal",
        "publication_candidate",
        "publication_candidate_projection_seal",
        "publication_candidate_projection",
        "publication_candidate_base_publication_commit",
        "publication_candidate_base_catalog",
        "publication_candidate_base_source",
        "publication_selection",
        "publication_stage_anchor",
        "publication_stage_order",
        "publication_stage_cursor_codec",
        "publication_stage_seal",
        "publication_stage",
        "publication_checkpoint_anchor",
        "publication_checkpoint_generation",
        "publication_checkpoint_cursor",
        "publication_checkpoint_processed_count",
        "publication_checkpoint_state",
        "publication_checkpoint_updated_at",
        "publication_checkpoint_seal",
        "publication_batch_receipt_anchor",
        "publication_batch_receipt_coordinate",
        "publication_batch_receipt_start_cursor",
        "publication_batch_receipt_start_processed_count",
        "publication_batch_receipt_next_cursor",
        "publication_batch_receipt_row_count",
        "publication_batch_receipt_committed_at",
        "publication_batch_receipt_seal",
        "publication_batch_receipt_stored",
        "publication_finalization_checkpoint_anchor",
        "publication_finalization_checkpoint_generation",
        "publication_finalization_checkpoint_cursor",
        "publication_finalization_checkpoint_processed_count",
        "publication_finalization_checkpoint_state",
        "publication_finalization_checkpoint_updated_at",
        "publication_finalization_checkpoint_seal",
        "publication_finalization_checkpoint",
        "publication_finalization_batch_receipt_anchor",
        "publication_finalization_batch_receipt_coordinate",
        "publication_finalization_batch_receipt_start_cursor",
        "publication_finalization_batch_receipt_start_processed_count",
        "publication_finalization_batch_receipt_next_cursor",
        "publication_finalization_batch_receipt_row_count",
        "publication_finalization_batch_receipt_committed_at",
        "publication_finalization_batch_receipt_seal",
        "publication_finalization_batch_receipt_stored",
        "publication_finalization_batch_receipt",
        "artifact_zip_writer_policy_anchor",
        "artifact_zip_writer_policy_zip_codec_version",
        "artifact_zip_writer_policy_compression_method",
        "artifact_zip_writer_policy_compression_level",
        "artifact_zip_writer_policy_dos_date",
        "artifact_zip_writer_policy_dos_time",
        "artifact_zip_writer_policy_unix_mode",
        "artifact_zip_writer_policy_general_purpose_flags",
        "artifact_zip_writer_policy_create_system",
        "artifact_zip_writer_policy_archive_name_codec_version",
        "artifact_zip_writer_policy_artifact_name_codec_version",
        "artifact_zip_writer_policy_identity",
        "artifact_zip_writer_policy_seal",
        "artifact_zip_writer_policy",
        "artifact_storage_codec_anchor",
        "artifact_storage_codec_adapter_id",
        "artifact_storage_codec_locator_codec_version",
        "artifact_storage_codec_protection_token_codec_version",
        "artifact_storage_codec_seal",
        "artifact_policy_semantics_anchor",
        "artifact_policy_semantics_artifact_algorithm_version",
        "artifact_policy_semantics_max_image_short_side",
        "artifact_policy_semantics_producer_fingerprint_sha256",
        "artifact_policy_semantics_identity",
        "artifact_policy_semantics_seal",
        "artifact_policy_semantics",
        "artifact_policy",
        "artifact_input",
        "artifact_delta_old",
        "artifact_delta_new",
        "artifact_operation",
        "artifact_blob",
        "catalog_revision_anchor",
        "catalog_revision_publication_count",
        "catalog_revision_descriptor_seal",
        "catalog_revision_descriptor",
        "catalog_revision",
        "catalog_revision_generation",
        "publication_generation_node",
        "publication_generation_successor",
        "display_title_policy_anchor",
        "display_title_policy_algorithm_version",
        "display_title_policy_title_sort_policy_id",
        "display_title_policy_identity",
        "display_title_policy_seal",
        "display_title_policy",
        "title_sort_policy_anchor",
        "title_sort_policy_algorithm_version",
        "title_sort_policy_unicode_data_version",
        "title_sort_policy_identity",
        "title_sort_policy_seal",
        "title_sort_policy",
        "display_title_choice",
        "title_sort",
        "catalog_publication_anchor",
        "catalog_publication_gallery_id",
        "catalog_publication_summary_sha256",
        "catalog_publication_language_sha256",
        "catalog_publication_modified_at",
        "catalog_publication_seal",
        "catalog_publication",
        "catalog_publication_order",
        "catalog_publication_title_anchor",
        "catalog_publication_title_source_title_sha256",
        "catalog_publication_title_source_gallery_name",
        "catalog_publication_title_seal",
        "catalog_publication_title",
        "catalog_publication_content",
        "contributor_role_registry",
        "catalog_contributor_anchor",
        "catalog_contributor_name_sha256",
        "catalog_contributor_role",
        "catalog_contributor_identity",
        "catalog_contributor_seal",
        "catalog_contributor",
        "catalog_subject",
        "publication_commit_anchor",
        "publication_commit_candidate",
        "publication_commit_catalog_revision",
        "publication_commit_source_revision",
        "publication_commit_generation",
        "publication_commit_operational_preparation",
        "publication_commit_operational_policy",
        "publication_commit_artifact_policy",
        "publication_commit_display_title_policy",
        "publication_commit_new_galleries",
        "publication_commit_changed_galleries",
        "publication_commit_removed_galleries",
        "publication_commit_duplicate_losers",
        "publication_commit_committed_at",
        "publication_commit_seal",
        "publication_commit",
        "publication_commit_finalization",
        "publication_commit_head_receipt",
        "publication_commit_head",
        "publication_receipt",
        "publication_head_revision",
        "publication_head_advanced_at",
        "publication_head",
        "prepared_artifact",
    }
)

# These compatibility and derived relations are generated non-materialized
# views.  They remain inside the physical-domain authority closure so the
# contract covers their exact output domains, but no writer family may claim
# them as a mutation target.
CATALOG_PHYSICAL_DOMAIN_READ_ONLY_RELATIONS = frozenset(
    {
        "canonical_value_allocation",
        "canonical_value_page",
        "canonical_value_page_descriptor",
        "file_name_identity",
        "gallery_observation_file",
        "tag_term",
        "source_build",
        "build_manifest",
        "gallery_manifest",
        "source_snapshot_manifest_identity",
        "artifact_producer_fingerprint",
        "artifact_storage_codec",
        "artifact_semantic_input",
        "prepared_artifact",
        "catalog_artifact",
        "gallery_observation_page_descriptor",
        "gallery_observation_page_key_bounds",
        "analysis_run",
        "analysis_state_anchor",
        "analysis_state_component_seal",
        "analysis_exclusion_delta",
        "analysis_file_hash_decision_shadow",
        "analysis_content_owner_candidate_shadow",
        "analysis_content_owner_shadow",
        "analysis_impacted_content",
        "analysis_impacted_gid",
        "analysis_gid_candidate_resolved",
        "analysis_gid_winner_shadow",
        "analysis_gid_winner_resolved",
        "analysis_checkpoint",
        "publication_checkpoint",
        "publication_batch_receipt",
        "publication_candidate",
        "publication_candidate_projection",
        "publication_candidate_base_catalog",
        "publication_candidate_base_source",
        "publication_stage",
        "publication_batch_receipt_stored",
        "publication_finalization_checkpoint",
        "publication_finalization_batch_receipt_stored",
        "publication_finalization_batch_receipt",
        "artifact_zip_writer_policy",
        "artifact_policy_semantics",
        "artifact_delta_old",
        "artifact_delta_new",
        "catalog_revision_descriptor",
        "catalog_revision",
        "catalog_revision_generation",
        "display_title_policy",
        "title_sort_policy",
        "catalog_publication",
        "catalog_publication_title",
        "catalog_contributor",
        "publication_commit",
        "publication_commit_head",
        "publication_receipt",
        "publication_head_revision",
        "publication_head_advanced_at",
        "publication_head",
    }
)
CATALOG_PHYSICAL_DOMAIN_MUTATION_RELATIONS = (
    CATALOG_PHYSICAL_DOMAIN_RELATIONS - CATALOG_PHYSICAL_DOMAIN_READ_ONLY_RELATIONS
)

_ANALYSIS_CHECKPOINT_WRITERS: tuple[PhysicalDomainEntrypoint, ...] = (
    AnalysisRepository.begin,
    AnalysisRepository.process_changed_gallery_batch,
    AnalysisRepository.process_changed_file_hash_batch,
    AnalysisRepository.process_file_hash_decision_batch,
    AnalysisRepository.validate_file_hash_decision_batch,
    AnalysisRepository.process_impacted_gallery_batch,
    AnalysisRepository.process_impacted_content_batch,
    AnalysisRepository.process_content_owner_candidate_batch,
    AnalysisRepository.validate_content_owner_candidate_batch,
    AnalysisRepository.process_content_owner_batch,
    AnalysisRepository.validate_content_owner_batch,
    AnalysisRepository.process_impacted_gid_batch,
    AnalysisRepository.process_gid_candidate_batch,
    AnalysisRepository.validate_gid_candidate_batch,
    AnalysisRepository.process_gid_winner_batch,
    AnalysisRepository.validate_gid_winner_batch,
)

_ARTIFACT_CHECKPOINT_WRITERS: tuple[PhysicalDomainEntrypoint, ...] = (
    ArtifactPreparationRepository.process_artifact_input_batch,
    ArtifactPreparationRepository.process_artifact_delta_operation_batch,
    ArtifactPreparationRepository.validate_artifact_input_delta_batch,
    ArtifactPreparationRepository.validate_prepared_artifact_batch,
    ArtifactPreparationRepository.validate_create_batch,
    ArtifactPreparationRepository.validate_rebuild_batch,
    ArtifactPreparationRepository.validate_delete_batch,
    ArtifactPreparationRepository.validate_unchanged_batch,
    ArtifactPreparationRepository.validate_new_gallery_batch,
    ArtifactPreparationRepository.validate_changed_gallery_batch,
    ArtifactPreparationRepository.validate_removed_gallery_batch,
    ArtifactPreparationRepository.validate_duplicate_loser_batch,
)

CATALOG_PHYSICAL_DOMAIN_WRITERS: tuple[PhysicalDomainEntrypoint, ...] = (
    CanonicalValueRepository.allocate,
    CanonicalValueRepository.put_page,
    ArtifactPreparationRepository.register_producer,
    GalleryIdentityRepository.handoff_locator,
    SourceBuildRepository.handoff_root,
    SourceBuildRepository.abandon,
    SourceBuildRepository.resolve_discovery_locator,
    SourceBuildRepository.assemble_batch,
    GalleryObservationStagingRepository.put_files,
    GalleryObservationStagingRepository.put_directories,
    GalleryObservationStagingRepository.put_tags,
    GalleryObservationStagingRepository.put_metadata,
    GalleryObservationStagingRepository.seal,
    AnalysisRepository.handoff_snapshot_manifest,
    AnalysisRepository.abandon,
    *_ANALYSIS_CHECKPOINT_WRITERS,
    PublicationCandidateRepository.begin,
    PublicationCandidateRepository.process_selection_batch,
    PublicationCandidateRepository.validate_selection_batch,
    PublicationCandidateRepository.process_catalog_projection_batch,
    PublicationCandidateRepository.validate_catalog_projection_batch,
    *_ARTIFACT_CHECKPOINT_WRITERS,
    ArtifactPreparationRepository.persist_prepared_artifact,
    ArtifactPreparationRepository.confirm_prepared_artifact,
    ArtifactReleaseRepository.commit_page,
    PublicationRepository.commit,
    PublicationFinalizationRepository.commit_page,
    VNextCleanupRepository.advance,
)

CATALOG_PHYSICAL_DOMAIN_GUARDS: tuple[PhysicalDomainGuard, ...] = (
    vnext_domains.require_ascii_bytes,
    vnext_domains.require_bool_byte,
    vnext_domains.require_bounded_bytes,
    vnext_domains.require_digest32,
    vnext_domains.require_enum_bytes,
    vnext_domains.require_int63,
    vnext_domains.require_positive_int63,
    vnext_domains.require_uint32,
    vnext_domains.require_utf8_bytes,
    vnext_domains.require_uuid16,
)


OPERATIONAL_PHYSICAL_DOMAIN_RELATIONS = frozenset(
    {
        "schema_epoch_control",
        "download_request",
        "deletion_request_url",
        "operational_preparation_checkpoint",
        "operational_preparation_effect_seal",
        "operational_event",
        "cleanup_checkpoint",
    }
)
OPERATIONAL_PHYSICAL_DOMAIN_MUTATION_RELATIONS = (
    OPERATIONAL_PHYSICAL_DOMAIN_RELATIONS - {"schema_epoch_control"}
)

OPERATIONAL_PHYSICAL_DOMAIN_WRITERS: tuple[PhysicalDomainEntrypoint, ...] = (
    VNextQueueRepository.request_download,
    VNextQueueRepository.ensure_download_request,
    VNextQueueRepository.complete_download_request,
    VNextQueueRepository.request_deletion,
    OperationalEffectRepository.begin,
    OperationalEffectRepository.append_batch,
    OperationalEffectRepository.seal,
    VNextCleanupRepository.begin_cycle,
    VNextCleanupRepository.advance,
)

# Epoch control has a different transaction owner.  Keep it as an explicit
# singleton family instead of falsely mixing it into caller-owned UOW methods.
OPERATIONAL_SCHEMA_EPOCH_WRITERS: tuple[PhysicalDomainEntrypoint, ...] = (
    SchemaEpochRunner.run,
)

OPERATIONAL_PHYSICAL_DOMAIN_GUARDS: tuple[PhysicalDomainGuard, ...] = (
    vnext_domains.require_bounded_bytes,
    vnext_domains.require_digest32,
    vnext_domains.require_int63,
    vnext_domains.require_positive_int63,
    vnext_domains.require_text,
    vnext_domains.require_uuid16,
)


def _validate_closed_family(
    entrypoints: tuple[PhysicalDomainEntrypoint, ...],
    guards: tuple[PhysicalDomainGuard, ...],
) -> None:
    if not entrypoints or len({id(value) for value in entrypoints}) != len(entrypoints):
        raise RuntimeError("physical-domain writer family is empty or duplicated")
    for entrypoint in entrypoints:
        module_name = getattr(entrypoint, "__module__", "")
        qualified_name = getattr(entrypoint, "__qualname__", "")
        parts = qualified_name.split(".")
        if (
            not module_name.startswith("h2hdb.")
            or len(parts) != 2
            or parts[1].startswith("_")
            or getattr(globals().get(parts[0]), parts[1], None) is not entrypoint
        ):
            raise RuntimeError(
                f"physical-domain entrypoint {module_name}.{qualified_name} "
                "is not an installed public method"
            )
    if not guards or len({id(value) for value in guards}) != len(guards):
        raise RuntimeError("physical-domain guard family is empty or duplicated")
    for guard in guards:
        name = getattr(guard, "__name__", "")
        if getattr(vnext_domains, name, None) is not guard:
            raise RuntimeError("physical-domain guard is not an installed symbol")


_validate_closed_family(
    CATALOG_PHYSICAL_DOMAIN_WRITERS,
    CATALOG_PHYSICAL_DOMAIN_GUARDS,
)
_validate_closed_family(
    OPERATIONAL_PHYSICAL_DOMAIN_WRITERS,
    OPERATIONAL_PHYSICAL_DOMAIN_GUARDS,
)
_validate_closed_family(
    OPERATIONAL_SCHEMA_EPOCH_WRITERS,
    (vnext_domains.require_int63,),
)
