import Std

/-!
# Generated schema artifact decode refinement

This model represents the closed primitive tree carried by the generated
schema resource.  The reference typed codec proves an exact round trip.  The
generic/build-time decoder is admitted only when its finite preflight envelope
is within the shipped byte/node/depth caps and it returns the exact source
tree.  The production theorem separately assumes that authentication selected
the exact generated bytes, which is the trust boundary that permits runtime to
reuse the build-time opcode proof.  Under those explicit assumptions, every
schema projection is unchanged.

The theorems are unbounded over encoded values, artifact trees, and projection
result types.  They do not prove that Python's pickle implementation, opcode
scanner and memo-graph abstraction, package resources, SHA-256 implementation
(including collision resistance), or handwritten runtime codec establishes
either the exact-byte or exact-decode premise.  Runtime structural
differential, property, adversarial DAG, fault, zipimport, wheel, and
resource-bound tests provide that refinement evidence.
-/

namespace H2HDB.Verification.SchemaArtifactDecode

mutual
inductive ArtifactTree where
  | null
  | boolean (value : Bool)
  | integer (value : Int)
  | string (value : String)
  | bytes (value : List UInt8)
  | list (values : ArtifactTrees)
  | tuple (values : ArtifactTrees)
  | dictionary (entries : ArtifactEntries)

inductive ArtifactTrees where
  | nil
  | cons (head : ArtifactTree) (tail : ArtifactTrees)

inductive ArtifactEntries where
  | nil
  | cons (key : String) (value : ArtifactTree) (tail : ArtifactEntries)
end

mutual
inductive RestrictedWire where
  | null
  | boolean (value : Bool)
  | integer (value : Int)
  | string (value : String)
  | byteString (value : List UInt8)
  | sequenceList (values : RestrictedWires)
  | sequenceTuple (values : RestrictedWires)
  | orderedDictionary (entries : RestrictedEntries)

inductive RestrictedWires where
  | nil
  | cons (head : RestrictedWire) (tail : RestrictedWires)

inductive RestrictedEntries where
  | nil
  | cons (key : String) (value : RestrictedWire) (tail : RestrictedEntries)
end

mutual
def encodeTree : ArtifactTree → RestrictedWire
  | .null => .null
  | .boolean value => .boolean value
  | .integer value => .integer value
  | .string value => .string value
  | .bytes value => .byteString value
  | .list values => .sequenceList (encodeTrees values)
  | .tuple values => .sequenceTuple (encodeTrees values)
  | .dictionary entries => .orderedDictionary (encodeEntries entries)

def encodeTrees : ArtifactTrees → RestrictedWires
  | .nil => .nil
  | .cons head tail => .cons (encodeTree head) (encodeTrees tail)

def encodeEntries : ArtifactEntries → RestrictedEntries
  | .nil => .nil
  | .cons key value tail =>
      .cons key (encodeTree value) (encodeEntries tail)
end

mutual
def decodeTree : RestrictedWire → ArtifactTree
  | .null => .null
  | .boolean value => .boolean value
  | .integer value => .integer value
  | .string value => .string value
  | .byteString value => .bytes value
  | .sequenceList values => .list (decodeTrees values)
  | .sequenceTuple values => .tuple (decodeTrees values)
  | .orderedDictionary entries => .dictionary (decodeEntries entries)

def decodeTrees : RestrictedWires → ArtifactTrees
  | .nil => .nil
  | .cons head tail => .cons (decodeTree head) (decodeTrees tail)

def decodeEntries : RestrictedEntries → ArtifactEntries
  | .nil => .nil
  | .cons key value tail =>
      .cons key (decodeTree value) (decodeEntries tail)
end

mutual
theorem reference_codec_roundtrip (tree : ArtifactTree) :
    decodeTree (encodeTree tree) = tree := by
  cases tree <;>
    simp [encodeTree, decodeTree, reference_trees_roundtrip,
      reference_entries_roundtrip]

theorem reference_trees_roundtrip (trees : ArtifactTrees) :
    decodeTrees (encodeTrees trees) = trees := by
  cases trees <;>
    simp [encodeTrees, decodeTrees, reference_codec_roundtrip,
      reference_trees_roundtrip]

theorem reference_entries_roundtrip (entries : ArtifactEntries) :
    decodeEntries (encodeEntries entries) = entries := by
  cases entries <;>
    simp [encodeEntries, decodeEntries, reference_codec_roundtrip,
      reference_entries_roundtrip]
end

theorem list_and_tuple_wires_are_distinct (values : ArtifactTrees) :
    encodeTree (.list values) ≠ encodeTree (.tuple values) := by
  intro contradiction
  cases contradiction

theorem string_and_bytes_wires_are_distinct
    (stringValue : String)
    (byteValue : List UInt8) :
    encodeTree (.string stringValue) ≠ encodeTree (.bytes byteValue) := by
  intro contradiction
  cases contradiction

structure Envelope where
  resourceBytes : Nat
  expandedBytes : Nat
  opcodes : Nat
  nodes : Nat
  depth : Nat
deriving DecidableEq, Repr

def maxResourceBytes : Nat := 8 * 1024 * 1024
def maxExpandedBytes : Nat := 32 * 1024 * 1024
def maxOpcodes : Nat := 2000000
def maxNodes : Nat := 1000000
def maxDepth : Nat := 64

def WithinBounds (envelope : Envelope) : Prop :=
  envelope.resourceBytes ≤ maxResourceBytes ∧
    envelope.expandedBytes ≤ maxExpandedBytes ∧
    envelope.opcodes ≤ maxOpcodes ∧
    envelope.nodes ≤ maxNodes ∧
    envelope.depth ≤ maxDepth

def SuccessfulExactDecode
    (decode : Encoded → Option ArtifactTree)
    (wire : Encoded)
    (source : ArtifactTree) : Prop :=
  decode wire = some source

def FullPreflightAdmitted
    (decode : Encoded → Option ArtifactTree)
    (wire : Encoded)
    (source : ArtifactTree)
    (envelope : Envelope) : Prop :=
  WithinBounds envelope ∧ SuccessfulExactDecode decode wire source

theorem admitted_payload_is_bounded
    (decode : Encoded → Option ArtifactTree)
    (wire : Encoded)
    (source : ArtifactTree)
    (envelope : Envelope)
    (admitted : FullPreflightAdmitted decode wire source envelope) :
    WithinBounds envelope := by
  exact admitted.1

theorem successful_exact_decode_preserves_projection
    (decode : Encoded → Option ArtifactTree)
    (wire : Encoded)
    (source : ArtifactTree)
    (project : ArtifactTree → Projection)
    (exact : SuccessfulExactDecode decode wire source) :
    (decode wire).map project = some (project source) := by
  simp [SuccessfulExactDecode] at exact
  simp [exact]

theorem admitted_decode_preserves_schema_projection
    (decode : Encoded → Option ArtifactTree)
    (wire : Encoded)
    (source : ArtifactTree)
    (envelope : Envelope)
    (project : ArtifactTree → Projection)
    (admitted : FullPreflightAdmitted decode wire source envelope) :
    (decode wire).map project = some (project source) := by
  exact successful_exact_decode_preserves_projection
    decode wire source project admitted.2

def ExactPinnedResource (observed generated : Encoded) : Prop :=
  observed = generated

def PinnedRuntimeAdmitted
    (decode : Encoded → Option ArtifactTree)
    (observed generated : Encoded)
    (source : ArtifactTree) : Prop :=
  ExactPinnedResource observed generated ∧
    SuccessfulExactDecode decode generated source

theorem pinned_runtime_decode_preserves_schema_projection
    (decode : Encoded → Option ArtifactTree)
    (observed generated : Encoded)
    (source : ArtifactTree)
    (project : ArtifactTree → Projection)
    (admitted : PinnedRuntimeAdmitted decode observed generated source) :
    (decode observed).map project = some (project source) := by
  rw [admitted.1]
  exact successful_exact_decode_preserves_projection
    decode generated source project admitted.2

end H2HDB.Verification.SchemaArtifactDecode
